/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ExportInquiryRouteImport } from './routes/export-inquiry'
import { Route as DistributorshipRouteImport } from './routes/distributorship'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as DistributorshipIndexRouteImport } from './routes/distributorship.index'
import { Route as ProductsBrandIdRouteImport } from './routes/products.$brandId'
import { Route as DistributorshipHappikeryRouteImport } from './routes/distributorship.happikery'
import { Route as DistributorshipBlsRouteImport } from './routes/distributorship.bls'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportInquiryRoute = ExportInquiryRouteImport.update({
  id: '/export-inquiry',
  path: '/export-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorshipRoute = DistributorshipRouteImport.update({
  id: '/distributorship',
  path: '/distributorship',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const DistributorshipIndexRoute = DistributorshipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistributorshipRoute,
} as any)
const ProductsBrandIdRoute = ProductsBrandIdRouteImport.update({
  id: '/$brandId',
  path: '/$brandId',
  getParentRoute: () => ProductsRoute,
} as any)
const DistributorshipHappikeryRoute =
  DistributorshipHappikeryRouteImport.update({
    id: '/happikery',
    path: '/happikery',
    getParentRoute: () => DistributorshipRoute,
  } as any)
const DistributorshipBlsRoute = DistributorshipBlsRouteImport.update({
  id: '/bls',
  path: '/bls',
  getParentRoute: () => DistributorshipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributorship': typeof DistributorshipRouteWithChildren
  '/export-inquiry': typeof ExportInquiryRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/distributorship/bls': typeof DistributorshipBlsRoute
  '/distributorship/happikery': typeof DistributorshipHappikeryRoute
  '/products/$brandId': typeof ProductsBrandIdRoute
  '/distributorship/': typeof DistributorshipIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/export-inquiry': typeof ExportInquiryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/distributorship/bls': typeof DistributorshipBlsRoute
  '/distributorship/happikery': typeof DistributorshipHappikeryRoute
  '/products/$brandId': typeof ProductsBrandIdRoute
  '/distributorship': typeof DistributorshipIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distributorship': typeof DistributorshipRouteWithChildren
  '/export-inquiry': typeof ExportInquiryRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/distributorship/bls': typeof DistributorshipBlsRoute
  '/distributorship/happikery': typeof DistributorshipHappikeryRoute
  '/products/$brandId': typeof ProductsBrandIdRoute
  '/distributorship/': typeof DistributorshipIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/distributorship'
    | '/export-inquiry'
    | '/products'
    | '/services'
    | '/sitemap.xml'
    | '/distributorship/bls'
    | '/distributorship/happikery'
    | '/products/$brandId'
    | '/distributorship/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/export-inquiry'
    | '/services'
    | '/sitemap.xml'
    | '/distributorship/bls'
    | '/distributorship/happikery'
    | '/products/$brandId'
    | '/distributorship'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/distributorship'
    | '/export-inquiry'
    | '/products'
    | '/services'
    | '/sitemap.xml'
    | '/distributorship/bls'
    | '/distributorship/happikery'
    | '/products/$brandId'
    | '/distributorship/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DistributorshipRoute: typeof DistributorshipRouteWithChildren
  ExportInquiryRoute: typeof ExportInquiryRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-inquiry': {
      id: '/export-inquiry'
      path: '/export-inquiry'
      fullPath: '/export-inquiry'
      preLoaderRoute: typeof ExportInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributorship': {
      id: '/distributorship'
      path: '/distributorship'
      fullPath: '/distributorship'
      preLoaderRoute: typeof DistributorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/distributorship/': {
      id: '/distributorship/'
      path: '/'
      fullPath: '/distributorship/'
      preLoaderRoute: typeof DistributorshipIndexRouteImport
      parentRoute: typeof DistributorshipRoute
    }
    '/products/$brandId': {
      id: '/products/$brandId'
      path: '/$brandId'
      fullPath: '/products/$brandId'
      preLoaderRoute: typeof ProductsBrandIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/distributorship/happikery': {
      id: '/distributorship/happikery'
      path: '/happikery'
      fullPath: '/distributorship/happikery'
      preLoaderRoute: typeof DistributorshipHappikeryRouteImport
      parentRoute: typeof DistributorshipRoute
    }
    '/distributorship/bls': {
      id: '/distributorship/bls'
      path: '/bls'
      fullPath: '/distributorship/bls'
      preLoaderRoute: typeof DistributorshipBlsRouteImport
      parentRoute: typeof DistributorshipRoute
    }
  }
}

interface DistributorshipRouteChildren {
  DistributorshipBlsRoute: typeof DistributorshipBlsRoute
  DistributorshipHappikeryRoute: typeof DistributorshipHappikeryRoute
  DistributorshipIndexRoute: typeof DistributorshipIndexRoute
}

const DistributorshipRouteChildren: DistributorshipRouteChildren = {
  DistributorshipBlsRoute: DistributorshipBlsRoute,
  DistributorshipHappikeryRoute: DistributorshipHappikeryRoute,
  DistributorshipIndexRoute: DistributorshipIndexRoute,
}

const DistributorshipRouteWithChildren = DistributorshipRoute._addFileChildren(
  DistributorshipRouteChildren,
)

interface ProductsRouteChildren {
  ProductsBrandIdRoute: typeof ProductsBrandIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBrandIdRoute: ProductsBrandIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DistributorshipRoute: DistributorshipRouteWithChildren,
  ExportInquiryRoute: ExportInquiryRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
